from langchain_core.prompts import PromptTemplate
from app.prompts.prompts import (
    SUMMARIZE_CONVERSATION_HISTORY_PROMPT,
    ASK_LLM_PROMPT,
    RAG_REWRITE_QUERY_PROMPT,
    WEB_REWRITE_QUERY_PROMPT,
    INPUT_GUARDRAIL_PROMPT,
    OUTPUT_GUARDRAIL_PROMPT,
    CONTENT_SECURITY_GUARDRAIL_PROMPT,
)

SUMMARIZE_CONVERSATION_HISTORY_PROMPT_TEMPLATE = PromptTemplate.from_template(SUMMARIZE_CONVERSATION_HISTORY_PROMPT)
RAG_REWRITE_QUERY_PROMPT_TEMPLATE = PromptTemplate.from_template(RAG_REWRITE_QUERY_PROMPT)
WEB_REWRITE_QUERY_PROMPT_TEMPLATE = PromptTemplate.from_template(WEB_REWRITE_QUERY_PROMPT)
ASK_LLM_PROMPT_TEMPLATE = PromptTemplate.from_template(ASK_LLM_PROMPT)
INPUT_GUARDRAIL_PROMPT_TEMPLATE = PromptTemplate.from_template(INPUT_GUARDRAIL_PROMPT)
OUTPUT_GUARDRAIL_PROMPT_TEMPLATE = PromptTemplate.from_template(OUTPUT_GUARDRAIL_PROMPT)
CONTENT_SECURITY_GUARDRAIL_PROMPT_TEMPLATE = PromptTemplate.from_template(CONTENT_SECURITY_GUARDRAIL_PROMPT)